import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-[20px]">
          <Link href={"/page1"}>
            <button>Page 1</button>
          </Link>
          <Link href={"/page2"}>
            <button>Page 2</button>
          </Link>
          <Link href={"/"}>
            <button>Home</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
